"""
Utility to merge shards generated by generate_arbiter_data.py
"""
import glob
import os

OUT_DIR  = "strategy6/data"
OUT_FILE = os.path.join(OUT_DIR, "arbiter_sft.jsonl")

def merge():
    shards = sorted(glob.glob(os.path.join(OUT_DIR, "arbiter_sft_shard_*.jsonl")))
    print(f"Found {len(shards)} shards: {shards}")
    
    with open(OUT_FILE, "w") as f_out:
        count = 0
        for s in shards:
            with open(s, "r") as f_in:
                for line in f_in:
                    f_out.write(line)
                    count += 1
            print(f"Merged {s}")
    
    print(f"Done! Merged {count} samples into {OUT_FILE}")

if __name__ == "__main__":
    merge()
